version: 0.2
env:
  variables:
    GENESYSCLOUD_API_REGION: "https://api.mypurecloud.com"
  parameter-store:
    GENESYSCLOUD_OAUTHCLIENT_ID: /CodeBuild/GENESYSCLOUD_OAUTHCLIENT_ID
    GENESYSCLOUD_OAUTHCLIENT_SECRET: /CodeBuild/GENESYSCLOUD_OAUTHCLIENT_SECRET
    GENESYSCLOUD_REGION: /CodeBuild/GENESYSCLOUD_REGION
phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update
      - sudo apt-get install terraform
      - pip install PureCloudPlatformClientV2
  pre_build:
    commands:
      # run script to destroy dangling resources
      - echo "We are in the pre build phase"
      - terraform --version
      - pip --version
      - python --version
      - go version
  build:
    commands:
      - echo "Entered the build phase..."
      - echo Build started on `date`
      - grep "Welcome" index.html
      - uname -a
      - echo Client ID $GENESYSCLOUD_OAUTHCLIENT_ID
      - echo Client Secret $GENESYSCLOUD_OAUTHCLIENT_SECRET
      - echo Region $GENESYSCLOUD_REGION
      - echo Deploying terraform infrastructure
      - cd terraform
      - terraform init
      - terraform apply --auto-approve
  post_build:
    commands:
      - pwd
      - cd ../scripts
      - echo "We are in the post build phase"
      - echo "Running platform tests"
      - python platform_tests.py
    finally:
      - cd ../terraform
      - terraform destroy --auto-approve


