version: 0.2
# env:
#   secrets-manager:
#     OAUTH_CLIENT_ID: "dev/charlie_genesyscloud_oauth_creds:CHARLIE_GENESYSCLOUD_OAUTHCLIENT_ID"
#     OAUTH_CLIENT_SECRET: "dev/charlie_genesyscloud_oauth_creds:CHARLIE_GENESYSCLOUD_OAUTHCLIENT_SECRET"
phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      # - echo "Installing terraform binary"
      # - yum -y update && yum install -y sudo
      # - sudo yum install -y yum-utils
      # - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      # - sudo yum -y install terraform

      - sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update
      - sudo apt-get install terraform
    # finally:
    #   - terraform -help
  pre_build:
    commands:
      - echo "We are in the pre build phase"
  build:
    commands:
      - echo "Entered the build phase..."
      - echo Build started on `date`
      - grep "Welcome" index.html
      - go version
      - uname -a
      - terraform --version
      # - echo "$OAUTH_CLIENT_ID"
  post_build:
    commands:
      - echo "We are in the post build phase"


